[build]
  command = "echo 'Frontend estático: nada para construir'"
  publish = "."
  ignore = "../backend/*"

[[redirects]]
  from = "/api/*"
  to = "https://stockmanager-production-aa4d.up.railway.app/api/:splat"
  status = 200
  force = true

[dev]
  targetPort = 3000